env:
  browser: true
  es2021: true
extends:
  - 'standard'
  - 'plugin:react/recommended'
  - 'eslint:recommended'
  - 'react-app'
  - 'prettier'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - prettier
rules:
  no-underscore-dangle: 0
  arrow-body-style: 0
  no-shadow: 0
  consistent-return: 0
  no-nested-ternary: 0
  no-case-declarations: 0
  no-duplicate-imports: 1
  no-console: 2
  no-extra-semi: 0
  no-multiple-empty-lines: 1
  import/no-duplicates: 0
  camelcase: 0
  new-cap: 0
  react-hooks/exhaustive-deps: 0
  react/prop-types: 0
